import type { Metadata } from 'next'
import { AuthProvider } from '@/hooks/authContext'
const Navbar = dynamic(() => import('@/components/Navbar'))
import Footer from '@/components/Footer'
import "./global.css"
import dynamic from 'next/dynamic'
export const metadata: Metadata = {
  title: 'Sport Equipments',
  description: 'Generated by create next app',
  icons: {
    icon: [
      "/logo.svg"
    ]
  }
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>
        <AuthProvider>
          <Navbar />
          {children}
          <Footer />
        </AuthProvider>
      </body>
    </html>
  )
}
