import type { Metadata } from 'next'
import './globals.css'
import { SearchProvider } from '@/hooks/searchContext'
import { AuthProvider } from '@/hooks/authContext'
import Navbar from '@/components/Navbar'
import Footer from '@/components/Footer'

export const metadata: Metadata = {
  title: 'App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>
        <SearchProvider>
          <AuthProvider>
            <Navbar />
            {children}
            <Footer />
          </AuthProvider>
        </SearchProvider>
      </body>
    </html>
  )
}
